# Generated by Django 3.2.5 on 2021-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.IntegerField(verbose_name='Telefono')),
                ('company', models.CharField(max_length=50, verbose_name='Compañia')),
                ('subject', models.CharField(max_length=50, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('paiss', models.CharField(choices=[('CHILE', 'CHILE'), ('PERU', 'PERU'), ('ARGENTINA', 'ARGENTINA'), ('BRASIL', 'BRASIL'), ('PARAGUAY', 'PARAGUAY')], default='CHILE', max_length=30)),
                ('pago', models.CharField(choices=[('PESO', 'PESO'), ('DOLAR', 'DOLAR')], default='PESO', max_length=30)),
                ('foto', models.ImageField(null=True, upload_to='', verbose_name='fotito')),
                ('num_ver', models.IntegerField(null=True, verbose_name='numero identificador')),
            ],
            options={
                'verbose_name': 'Formulario Contacto',
                'verbose_name_plural': 'Formularios Contactos',
            },
        ),
    ]
